// Package usergen provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package usergen

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for DetectJobStatusStatus.
const (
	DetectJobStatusStatusCompleted  DetectJobStatusStatus = "completed"
	DetectJobStatusStatusFailed     DetectJobStatusStatus = "failed"
	DetectJobStatusStatusPending    DetectJobStatusStatus = "pending"
	DetectJobStatusStatusProcessing DetectJobStatusStatus = "processing"
)

// Defines values for ErrorResponseCode.
const (
	CONFLICT           ErrorResponseCode = "CONFLICT"
	FORBIDDEN          ErrorResponseCode = "FORBIDDEN"
	INTERNAL           ErrorResponseCode = "INTERNAL"
	INVALIDINPUT       ErrorResponseCode = "INVALID_INPUT"
	INVALIDTOKEN       ErrorResponseCode = "INVALID_TOKEN"
	MISSINGFIELD       ErrorResponseCode = "MISSING_FIELD"
	NOTFOUND           ErrorResponseCode = "NOT_FOUND"
	QUOTAEXCEEDED      ErrorResponseCode = "QUOTA_EXCEEDED"
	RATELIMITED        ErrorResponseCode = "RATE_LIMITED"
	SERVICEUNAVAILABLE ErrorResponseCode = "SERVICE_UNAVAILABLE"
	UPSTREAMERROR      ErrorResponseCode = "UPSTREAM_ERROR"
	UPSTREAMTIMEOUT    ErrorResponseCode = "UPSTREAM_TIMEOUT"
)

// Defines values for FeedbackSubmitRequestAction.
const (
	ItemSwapped FeedbackSubmitRequestAction = "item_swapped"
	Rated       FeedbackSubmitRequestAction = "rated"
	Regenerated FeedbackSubmitRequestAction = "regenerated"
	Saved       FeedbackSubmitRequestAction = "saved"
	Skipped     FeedbackSubmitRequestAction = "skipped"
)

// Defines values for GoogleAuthResponseMode.
const (
	Live GoogleAuthResponseMode = "live"
)

// Defines values for MockLoginRequestProvider.
const (
	Google MockLoginRequestProvider = "google"
)

// Defines values for MockLoginResponseMode.
const (
	Mock MockLoginResponseMode = "mock"
)

// Defines values for MoodboardOutfitLayoutRoles.
const (
	MoodboardOutfitLayoutRolesAccent  MoodboardOutfitLayoutRoles = "accent"
	MoodboardOutfitLayoutRolesHero    MoodboardOutfitLayoutRoles = "hero"
	MoodboardOutfitLayoutRolesSupport MoodboardOutfitLayoutRoles = "support"
)

// Defines values for MoodboardOutfitVisualWeights.
const (
	MoodboardOutfitVisualWeightsMinor      MoodboardOutfitVisualWeights = "minor"
	MoodboardOutfitVisualWeightsStatement  MoodboardOutfitVisualWeights = "statement"
	MoodboardOutfitVisualWeightsSupporting MoodboardOutfitVisualWeights = "supporting"
)

// Defines values for OutfitLayoutRoles.
const (
	OutfitLayoutRolesAccent  OutfitLayoutRoles = "accent"
	OutfitLayoutRolesHero    OutfitLayoutRoles = "hero"
	OutfitLayoutRolesSupport OutfitLayoutRoles = "support"
)

// Defines values for OutfitVisualWeights.
const (
	OutfitVisualWeightsMinor      OutfitVisualWeights = "minor"
	OutfitVisualWeightsStatement  OutfitVisualWeights = "statement"
	OutfitVisualWeightsSupporting OutfitVisualWeights = "supporting"
)

// Defines values for OutfitJobStatusStatus.
const (
	OutfitJobStatusStatusCompleted  OutfitJobStatusStatus = "completed"
	OutfitJobStatusStatusFailed     OutfitJobStatusStatus = "failed"
	OutfitJobStatusStatusPending    OutfitJobStatusStatus = "pending"
	OutfitJobStatusStatusProcessing OutfitJobStatusStatus = "processing"
)

// Defines values for ReadinessResponseRedis.
const (
	Absent ReadinessResponseRedis = "absent"
	Down   ReadinessResponseRedis = "down"
	Up     ReadinessResponseRedis = "up"
)

// Defines values for ReadinessResponseStatus.
const (
	NotReady ReadinessResponseStatus = "not_ready"
	Ready    ReadinessResponseStatus = "ready"
)

// Defines values for WeatherUnit.
const (
	WeatherUnitC WeatherUnit = "C"
	WeatherUnitF WeatherUnit = "F"
)

// Defines values for GetOutfitsParamsUnit.
const (
	GetOutfitsParamsUnitC GetOutfitsParamsUnit = "C"
	GetOutfitsParamsUnitF GetOutfitsParamsUnit = "F"
)

// Defines values for SubmitOutfitGenerationParamsUnit.
const (
	C SubmitOutfitGenerationParamsUnit = "C"
	F SubmitOutfitGenerationParamsUnit = "F"
)

// AuthUser Authenticated user surfaced in every auth response.
type AuthUser struct {
	AvatarUrl *string             `json:"avatarUrl,omitempty"`
	Email     openapi_types.Email `json:"email"`
	Id        string              `json:"id"`
	Name      string              `json:"name"`
}

// BrandsResponse defines model for BrandsResponse.
type BrandsResponse struct {
	Brands []string `json:"brands"`
}

// ClientHealthResponse RN-app version sentinel (mootd#40). The app polls on
// foreground; when its own version is below
// `minClientVersion`, it renders a blocking "please
// update" sheet. `maintenance: true` shows a soft
// banner.
type ClientHealthResponse struct {
	Maintenance      bool   `json:"maintenance"`
	MinClientVersion string `json:"minClientVersion"`
	Sha              string `json:"sha"`
	Version          string `json:"version"`
}

// ClothingItem A persisted garment in the caller's wardrobe.
type ClothingItem struct {
	Category  string    `json:"category"`
	CreatedAt time.Time `json:"createdAt"`
	Id        string    `json:"id"`
	ImageUrl  string    `json:"imageUrl"`
	Label     string    `json:"label"`

	// PngImageUrl Background-removed PNG; populated asynchronously by the bg-removal worker.
	PngImageUrl *string           `json:"pngImageUrl,omitempty"`
	Traits      map[string]string `json:"traits"`
	UserId      string            `json:"userId"`
}

// DetectJobStatus Polled state of an async detection job. `status`
// progresses pending → processing → completed | failed.
type DetectJobStatus struct {
	Error  *string               `json:"error,omitempty"`
	Items  *[]DetectedItem       `json:"items,omitempty"`
	Status DetectJobStatusStatus `json:"status"`
}

// DetectJobStatusStatus defines model for DetectJobStatus.Status.
type DetectJobStatusStatus string

// DetectJobSubmitResponse Async detection job created from POST
// /v1/wardrobe/detect-jobs. Poll the matching GET
// /v1/wardrobe/detect-jobs/{id} for status.
type DetectJobSubmitResponse struct {
	JobId string `json:"jobId"`
}

// DetectResponse defines model for DetectResponse.
type DetectResponse struct {
	Items []DetectedItem `json:"items"`
}

// DetectedItem Client-facing representation of one detected garment
// returned immediately from POST /v1/wardrobe/detect
// (before the user reviews + commits).
type DetectedItem struct {
	Category    string             `json:"category"`
	Confidence  *float64           `json:"confidence,omitempty"`
	Id          string             `json:"id"`
	ImageUrl    *string            `json:"imageUrl,omitempty"`
	Label       string             `json:"label"`
	PngImageUrl *string            `json:"pngImageUrl,omitempty"`
	Traits      *map[string]string `json:"traits,omitempty"`
}

// ErrorResponse Canonical error body. `error` is human-readable; `code`
// is the stable machine-readable identifier (mootd#41) —
// switch on `code` for retry / branch decisions, never on
// the message. `requestId` echoes the X-Request-ID
// response header for log correlation.
type ErrorResponse struct {
	Code  *ErrorResponseCode `json:"code,omitempty"`
	Error string             `json:"error"`

	// RequestId Request correlation ID; echoes X-Request-ID.
	RequestId *string `json:"requestId,omitempty"`

	// RetryAfter When `code=RATE_LIMITED` or `QUOTA_EXCEEDED`, seconds until retry is allowed.
	RetryAfter *int `json:"retryAfter,omitempty"`
}

// ErrorResponseCode defines model for ErrorResponse.Code.
type ErrorResponseCode string

// EventValidationError defines model for EventValidationError.
type EventValidationError struct {
	// Index Position in the original request.events array.
	Index  int    `json:"index"`
	Reason string `json:"reason"`
}

// FeedbackContext Coarse, non-PII signals attached to a feedback event.
type FeedbackContext struct {
	Archetype *string `json:"archetype,omitempty"`
	DayOfWeek *string `json:"dayOfWeek,omitempty"`
	Hour      *int    `json:"hour,omitempty"`
	Occasion  *string `json:"occasion,omitempty"`
	Weather   *string `json:"weather,omitempty"`
}

// FeedbackSubmitRequest POST /v1/outfits/feedback body. UserID is taken from
// the JWT — clients can't forge events for other users.
type FeedbackSubmitRequest struct {
	Action         FeedbackSubmitRequestAction `json:"action"`
	ChosenOutfitId *string                     `json:"chosenOutfitId,omitempty"`

	// Context Coarse, non-PII signals attached to a feedback event.
	Context          *FeedbackContext  `json:"context,omitempty"`
	GeneratedBatch   *[]OutfitSnapshot `json:"generatedBatch,omitempty"`
	GeneratorVersion *string           `json:"generatorVersion,omitempty"`
	JobId            *string           `json:"jobId,omitempty"`
	PromptVersion    *string           `json:"promptVersion,omitempty"`
	Rating           *int              `json:"rating,omitempty"`

	// SwappedFrom Wardrobe item ID swapped out (action=item_swapped).
	SwappedFrom *string `json:"swappedFrom,omitempty"`

	// SwappedTo Wardrobe item ID swapped in (action=item_swapped).
	SwappedTo *string `json:"swappedTo,omitempty"`
}

// FeedbackSubmitRequestAction defines model for FeedbackSubmitRequest.Action.
type FeedbackSubmitRequestAction string

// FeedbackSubmitResponse defines model for FeedbackSubmitResponse.
type FeedbackSubmitResponse struct {
	Id string `json:"id"`
}

// GenerateResponse Synchronous generate result (deprecated; prefer async).
type GenerateResponse struct {
	Outfits []Outfit `json:"outfits"`
}

// GenericItem defines model for GenericItem.
type GenericItem struct {
	ArchetypeScores  map[string]float64 `json:"archetypeScores"`
	Category         string             `json:"category"`
	CreatedAt        time.Time          `json:"createdAt"`
	DedupKey         *string            `json:"dedupKey,omitempty"`
	Description      *string            `json:"description,omitempty"`
	Id               string             `json:"id"`
	ImageUrl         string             `json:"imageUrl"`
	Label            string             `json:"label"`
	PngImageUrl      *string            `json:"pngImageUrl,omitempty"`
	PrimaryArchetype string             `json:"primaryArchetype"`
	Traits           map[string]string  `json:"traits"`
	UsageCount       *int               `json:"usageCount,omitempty"`
}

// GenericItemsList defines model for GenericItemsList.
type GenericItemsList struct {
	Items []GenericItem `json:"items"`
}

// GoogleAuthRequest Body for POST /v1/auth/google. The backend verifies
// `accessToken` with Google directly and extracts user
// info — client-supplied profile fields are intentionally
// not accepted.
type GoogleAuthRequest struct {
	// AccessToken Google OAuth access token from expo-auth-session.
	AccessToken string `json:"accessToken"`
}

// GoogleAuthResponse defines model for GoogleAuthResponse.
type GoogleAuthResponse struct {
	AccessToken  string                 `json:"accessToken"`
	ExpiresAt    time.Time              `json:"expiresAt"`
	Mode         GoogleAuthResponseMode `json:"mode"`
	RefreshToken string                 `json:"refreshToken"`

	// User Authenticated user surfaced in every auth response.
	User AuthUser `json:"user"`
}

// GoogleAuthResponseMode defines model for GoogleAuthResponse.Mode.
type GoogleAuthResponseMode string

// IngestEvent One event in a batch ingest. `name` MUST be a member
// of the catalog (the backend rejects unknown names).
type IngestEvent struct {
	// Name Catalog name. Current allowlist (18 events):
	// app_opened, screen_view, session_start,
	// session_heartbeat, session_end, photo_uploaded,
	// items_detected, item_confirmed, item_rejected,
	// generate_outfit_requested, generated_outfit,
	// viewed_outfit, rated_outfit, swapped_item,
	// saved_moodboard, viewed_calendar_date,
	// shared_moodboard, signed_up, signed_in,
	// signed_out.
	Name       string                  `json:"name"`
	Properties *map[string]interface{} `json:"properties,omitempty"`
	SessionId  string                  `json:"sessionId"`
}

// IngestRequest Batch envelope. Body capped at 128KB by middleware;
// events past the 500-per-request cap rejected.
type IngestRequest struct {
	Events []IngestEvent `json:"events"`
}

// IngestResponse Echoes per-event outcome. Invalid events don't poison
// the batch — accepted count + rejected indices/reasons
// are returned together.
type IngestResponse struct {
	Accepted int                     `json:"accepted"`
	Rejected *[]EventValidationError `json:"rejected,omitempty"`
}

// LivenessResponse defines model for LivenessResponse.
type LivenessResponse struct {
	Service string  `json:"service"`
	Status  string  `json:"status"`
	TimeUtc *string `json:"time_utc,omitempty"`
}

// LogoutRequest Body for POST /v1/auth/logout. Single-use: presenting a
// valid refresh token revokes it server-side. Best-effort:
// failures don't surface to the client.
type LogoutRequest struct {
	RefreshToken string `json:"refreshToken"`
}

// MockLoginRequest Body for POST /v1/auth/mock-login. Only valid in
// development — registration of the route is gated on
// ENVIRONMENT != production.
type MockLoginRequest struct {
	Provider MockLoginRequestProvider `json:"provider"`
}

// MockLoginRequestProvider defines model for MockLoginRequest.Provider.
type MockLoginRequestProvider string

// MockLoginResponse defines model for MockLoginResponse.
type MockLoginResponse struct {
	AccessToken  string                `json:"accessToken"`
	ExpiresAt    time.Time             `json:"expiresAt"`
	Mode         MockLoginResponseMode `json:"mode"`
	RefreshToken string                `json:"refreshToken"`

	// User Authenticated user surfaced in every auth response.
	User AuthUser `json:"user"`
}

// MockLoginResponseMode defines model for MockLoginResponse.Mode.
type MockLoginResponseMode string

// MoodboardListResponse defines model for MoodboardListResponse.
type MoodboardListResponse struct {
	Moodboards []SavedMoodBoard `json:"moodboards"`
	NextCursor *string          `json:"nextCursor"`
}

// MoodboardOutfit defines model for MoodboardOutfit.
type MoodboardOutfit struct {
	// ArchetypeScores Per-outfit archetype alignment.
	ArchetypeScores *map[string]float64 `json:"archetypeScores,omitempty"`
	BackgroundId    *string             `json:"backgroundId,omitempty"`
	BackgroundUrl   *string             `json:"backgroundUrl,omitempty"`
	Description     string              `json:"description"`
	Id              *string             `json:"id,omitempty"`

	// Items Wardrobe item IDs referenced by this outfit.
	Items []string `json:"items"`

	// LayoutRoles itemID → render role.
	LayoutRoles *map[string]MoodboardOutfitLayoutRoles `json:"layoutRoles,omitempty"`
	Name        string                                 `json:"name"`

	// Palette Dominant colors per item as
	Palette  *[]string `json:"palette,omitempty"`
	PanelId  *string   `json:"panelId,omitempty"`
	PanelUrl *string   `json:"panelUrl,omitempty"`

	// Rationale One-line stylist explanation tied to archetype/weather.
	Rationale *string `json:"rationale,omitempty"`

	// SmartSuggestion Archetype-driven item suggestion (small wardrobes).
	SmartSuggestion *string               `json:"smartSuggestion,omitempty"`
	Snapshots       *[]OutfitItemSnapshot `json:"snapshots,omitempty"`

	// Suggestions Hints for complementary items not in the wardrobe.
	Suggestions *[]string `json:"suggestions,omitempty"`

	// VisualWeights itemID → visual weight; flags the signature piece per outfit.
	VisualWeights *map[string]MoodboardOutfitVisualWeights `json:"visualWeights,omitempty"`

	// Weather Weather context attached to outfit generation +
	// moodboard saves. All fields optional.
	Weather *Weather `json:"weather,omitempty"`
}

// MoodboardOutfitLayoutRoles defines model for MoodboardOutfit.LayoutRoles.
type MoodboardOutfitLayoutRoles string

// MoodboardOutfitVisualWeights defines model for MoodboardOutfit.VisualWeights.
type MoodboardOutfitVisualWeights string

// Outfit A suggested outfit. Items reference wardrobe item IDs.
// Surface fields (panelId/Url, backgroundId/Url) carry
// the LLM's choice of moodboard texture.
type Outfit struct {
	// ArchetypeScores Per-outfit archetype alignment.
	ArchetypeScores *map[string]float64 `json:"archetypeScores,omitempty"`
	BackgroundId    *string             `json:"backgroundId,omitempty"`
	BackgroundUrl   *string             `json:"backgroundUrl,omitempty"`
	Description     string              `json:"description"`
	Id              *string             `json:"id,omitempty"`

	// Items Wardrobe item IDs referenced by this outfit.
	Items []string `json:"items"`

	// LayoutRoles itemID → render role.
	LayoutRoles *map[string]OutfitLayoutRoles `json:"layoutRoles,omitempty"`
	Name        string                        `json:"name"`

	// Palette Dominant colors per item as
	Palette  *[]string `json:"palette,omitempty"`
	PanelId  *string   `json:"panelId,omitempty"`
	PanelUrl *string   `json:"panelUrl,omitempty"`

	// Rationale One-line stylist explanation tied to archetype/weather.
	Rationale *string `json:"rationale,omitempty"`

	// SmartSuggestion Archetype-driven item suggestion (small wardrobes).
	SmartSuggestion *string `json:"smartSuggestion,omitempty"`

	// Suggestions Hints for complementary items not in the wardrobe.
	Suggestions *[]string `json:"suggestions,omitempty"`

	// VisualWeights itemID → visual weight; flags the signature piece per outfit.
	VisualWeights *map[string]OutfitVisualWeights `json:"visualWeights,omitempty"`

	// Weather Weather context attached to outfit generation +
	// moodboard saves. All fields optional.
	Weather *Weather `json:"weather,omitempty"`
}

// OutfitLayoutRoles defines model for Outfit.LayoutRoles.
type OutfitLayoutRoles string

// OutfitVisualWeights defines model for Outfit.VisualWeights.
type OutfitVisualWeights string

// OutfitItemSnapshot Snapshot of a wardrobe item embedded in a saved
// moodboard so the card stays renderable after the
// original item is deleted/edited.
type OutfitItemSnapshot struct {
	Category    string  `json:"category"`
	Id          string  `json:"id"`
	ImageUrl    string  `json:"imageUrl"`
	Label       string  `json:"label"`
	PngImageUrl *string `json:"pngImageUrl,omitempty"`
}

// OutfitJobStatus Polled state of an async outfit-generation job. Same
// progression as detect jobs (pending → processing →
// completed | failed).
type OutfitJobStatus struct {
	Error   *string               `json:"error,omitempty"`
	Outfits *[]Outfit             `json:"outfits,omitempty"`
	Status  OutfitJobStatusStatus `json:"status"`
}

// OutfitJobStatusStatus defines model for OutfitJobStatus.Status.
type OutfitJobStatusStatus string

// OutfitJobSubmitResponse Created from POST /v1/outfits/generate.
type OutfitJobSubmitResponse struct {
	JobId string `json:"jobId"`
}

// OutfitSnapshot Trimmed outfit shape preserved on a feedback event so
// training jobs don't need to cross-reference a
// moodboard row that may later be deleted.
type OutfitSnapshot struct {
	ArchetypeScores *map[string]float64 `json:"archetypeScores,omitempty"`
	Id              string              `json:"id"`
	Items           []string            `json:"items"`
	Name            *string             `json:"name,omitempty"`
	Rationale       *string             `json:"rationale,omitempty"`
}

// PurgeReport Result of a successful self-purge. `collections` maps
// each affected collection name to the number of
// documents deleted; `total` is the sum.
type PurgeReport struct {
	Collections map[string]int64 `json:"collections"`
	PurgedAt    time.Time        `json:"purgedAt"`
	Total       int64            `json:"total"`
	UserId      string           `json:"userId"`
}

// ReadinessResponse defines model for ReadinessResponse.
type ReadinessResponse struct {
	Mongo *string `json:"mongo,omitempty"`

	// Reason Set when status=not_ready.
	Reason  *string                 `json:"reason,omitempty"`
	Redis   *ReadinessResponseRedis `json:"redis,omitempty"`
	Service string                  `json:"service"`
	Status  ReadinessResponseStatus `json:"status"`
}

// ReadinessResponseRedis defines model for ReadinessResponse.Redis.
type ReadinessResponseRedis string

// ReadinessResponseStatus defines model for ReadinessResponse.Status.
type ReadinessResponseStatus string

// RefreshRequest defines model for RefreshRequest.
type RefreshRequest struct {
	RefreshToken string `json:"refreshToken"`
}

// RefreshResponse defines model for RefreshResponse.
type RefreshResponse struct {
	AccessToken  string    `json:"accessToken"`
	ExpiresAt    time.Time `json:"expiresAt"`
	RefreshToken string    `json:"refreshToken"`

	// User Authenticated user surfaced in every auth response.
	User AuthUser `json:"user"`
}

// SaveBrandRequest defines model for SaveBrandRequest.
type SaveBrandRequest struct {
	Name string `json:"name"`
}

// SaveMoodboardRequest defines model for SaveMoodboardRequest.
type SaveMoodboardRequest struct {
	// BoardImage Base64-encoded collage PNG (with or without
	// data: URL prefix). Optional; when present, stored
	// in GridFS and surfaced as imageUrl.
	BoardImage *string `json:"boardImage,omitempty"`

	// Date YYYY-MM-DD; today is used when empty.
	Date *string `json:"date,omitempty"`

	// GeneratedBatch Full set of outfits the user was shown. Strongly
	// recommended — without it preference pairs can't be
	// reconstructed for ranker training.
	GeneratedBatch *[]Outfit `json:"generatedBatch,omitempty"`

	// JobId Ties the save back to the generation job.
	JobId *string `json:"jobId,omitempty"`

	// Outfit Inlined outfit on a SavedMoodBoard. Same shape as
	// Outfit but with `snapshots` carrying resolved item
	// data so the card renders even after items are deleted.
	Outfit MoodboardOutfit `json:"outfit"`
}

// SavedMoodBoard defines model for SavedMoodBoard.
type SavedMoodBoard struct {
	CreatedAt time.Time `json:"createdAt"`

	// Date Calendar date in YYYY-MM-DD.
	Date string `json:"date"`
	Id   string `json:"id"`

	// ImageUrl Pre-rendered collage PNG (GridFS-backed). Populated
	// only when the client supplied `boardImage` on save.
	ImageUrl *string `json:"imageUrl,omitempty"`

	// Outfit Inlined outfit on a SavedMoodBoard. Same shape as
	// Outfit but with `snapshots` carrying resolved item
	// data so the card renders even after items are deleted.
	Outfit MoodboardOutfit `json:"outfit"`
	UserId string          `json:"userId"`
}

// SearchProduct One result from the external clothing-search service.
type SearchProduct struct {
	Id       string `json:"id"`
	ImageUrl string `json:"imageUrl"`

	// Price Pre-formatted human display string ("$49.99").
	Price  *string `json:"price,omitempty"`
	Source string  `json:"source"`
	Title  string  `json:"title"`
}

// SearchRequest defines model for SearchRequest.
type SearchRequest struct {
	Brand *string `json:"brand,omitempty"`
}

// SearchResponse defines model for SearchResponse.
type SearchResponse struct {
	Results []SearchProduct `json:"results"`
}

// UpdateProfileRequest Body for PUT /v1/user/profile. Every field is
// optional; at least one must be supplied.
type UpdateProfileRequest struct {
	AvatarUrl *string `json:"avatarUrl,omitempty"`

	// Creativity Update the outfit creativity preference
	// (mootd#67). Out-of-range values are clamped
	// server-side rather than rejected.
	Creativity *float64 `json:"creativity,omitempty"`
	Name       *string  `json:"name,omitempty"`
}

// UpdateWardrobeItemRequest Body for PATCH /v1/wardrobe/items/{id}. Subset of
// fields are mutable; at least one must be supplied.
type UpdateWardrobeItemRequest struct {
	Category *string            `json:"category,omitempty"`
	Label    *string            `json:"label,omitempty"`
	Traits   *map[string]string `json:"traits,omitempty"`
}

// UserDocument Authenticated user's profile. Returned from GET / PUT
// /v1/user/profile. `archetypeProfile` is the per-style
// affinity vector populated by the wardrobe analysis
// pipeline.
type UserDocument struct {
	ArchetypeProfile *map[string]float64 `json:"archetypeProfile,omitempty"`
	AvatarUrl        *string             `json:"avatarUrl,omitempty"`
	CreatedAt        time.Time           `json:"createdAt"`

	// Creativity Outfit-generation variance preference (mootd#67).
	// 0 = predictable / play-it-safe; 0.5 = current
	// historical default; 1 = surprise me. Backend
	// translates to LLM temperature via a piecewise-
	// linear map (0 → 0.5, 0.5 → 0.9, 1 → 1.2).
	// Missing field treated as 0.5.
	Creativity *float64            `json:"creativity,omitempty"`
	Email      openapi_types.Email `json:"email"`
	GoogleId   *string             `json:"googleId,omitempty"`
	Id         string              `json:"id"`
	Name       string              `json:"name"`
	UpdatedAt  time.Time           `json:"updatedAt"`
}

// WardrobeItemListResponse Paginated wardrobe items, newest first. nextCursor is
// empty when no more rows.
type WardrobeItemListResponse struct {
	Items      []ClothingItem `json:"items"`
	NextCursor *string        `json:"nextCursor,omitempty"`
}

// Weather Weather context attached to outfit generation +
// moodboard saves. All fields optional.
type Weather struct {
	Condition   *string      `json:"condition,omitempty"`
	Temperature *string      `json:"temperature,omitempty"`
	Unit        *WeatherUnit `json:"unit,omitempty"`
}

// WeatherUnit defines model for Weather.Unit.
type WeatherUnit string

// BadRequest Canonical error body. `error` is human-readable; `code`
// is the stable machine-readable identifier (mootd#41) —
// switch on `code` for retry / branch decisions, never on
// the message. `requestId` echoes the X-Request-ID
// response header for log correlation.
type BadRequest = ErrorResponse

// NotFound Canonical error body. `error` is human-readable; `code`
// is the stable machine-readable identifier (mootd#41) —
// switch on `code` for retry / branch decisions, never on
// the message. `requestId` echoes the X-Request-ID
// response header for log correlation.
type NotFound = ErrorResponse

// RateLimited Canonical error body. `error` is human-readable; `code`
// is the stable machine-readable identifier (mootd#41) —
// switch on `code` for retry / branch decisions, never on
// the message. `requestId` echoes the X-Request-ID
// response header for log correlation.
type RateLimited = ErrorResponse

// Unauthorized Canonical error body. `error` is human-readable; `code`
// is the stable machine-readable identifier (mootd#41) —
// switch on `code` for retry / branch decisions, never on
// the message. `requestId` echoes the X-Request-ID
// response header for log correlation.
type Unauthorized = ErrorResponse

// SearchBrandsParams defines parameters for SearchBrands.
type SearchBrandsParams struct {
	Q *string `form:"q,omitempty" json:"q,omitempty"`
}

// ListMoodboardsParams defines parameters for ListMoodboards.
type ListMoodboardsParams struct {
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *int    `form:"limit,omitempty" json:"limit,omitempty"`
}

// GetOutfitsParams defines parameters for GetOutfits.
type GetOutfitsParams struct {
	Temperature *string               `form:"temperature,omitempty" json:"temperature,omitempty"`
	Condition   *string               `form:"condition,omitempty" json:"condition,omitempty"`
	Unit        *GetOutfitsParamsUnit `form:"unit,omitempty" json:"unit,omitempty"`
}

// GetOutfitsParamsUnit defines parameters for GetOutfits.
type GetOutfitsParamsUnit string

// SubmitOutfitGenerationParams defines parameters for SubmitOutfitGeneration.
type SubmitOutfitGenerationParams struct {
	Temperature    *string                           `form:"temperature,omitempty" json:"temperature,omitempty"`
	Condition      *string                           `form:"condition,omitempty" json:"condition,omitempty"`
	Unit           *SubmitOutfitGenerationParamsUnit `form:"unit,omitempty" json:"unit,omitempty"`
	IdempotencyKey *string                           `json:"Idempotency-Key,omitempty"`
}

// SubmitOutfitGenerationParamsUnit defines parameters for SubmitOutfitGeneration.
type SubmitOutfitGenerationParamsUnit string

// DetectFromPhotoMultipartBody defines parameters for DetectFromPhoto.
type DetectFromPhotoMultipartBody struct {
	Photo openapi_types.File `json:"photo"`
}

// SubmitDetectJobMultipartBody defines parameters for SubmitDetectJob.
type SubmitDetectJobMultipartBody struct {
	Photo openapi_types.File `json:"photo"`
}

// ListWardrobeItemsParams defines parameters for ListWardrobeItems.
type ListWardrobeItemsParams struct {
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *int    `form:"limit,omitempty" json:"limit,omitempty"`
}

// SignInWithGoogleJSONRequestBody defines body for SignInWithGoogle for application/json ContentType.
type SignInWithGoogleJSONRequestBody = GoogleAuthRequest

// SignOutJSONRequestBody defines body for SignOut for application/json ContentType.
type SignOutJSONRequestBody = LogoutRequest

// SignInWithMockJSONRequestBody defines body for SignInWithMock for application/json ContentType.
type SignInWithMockJSONRequestBody = MockLoginRequest

// RefreshTokensJSONRequestBody defines body for RefreshTokens for application/json ContentType.
type RefreshTokensJSONRequestBody = RefreshRequest

// SaveBrandJSONRequestBody defines body for SaveBrand for application/json ContentType.
type SaveBrandJSONRequestBody = SaveBrandRequest

// IngestEventsJSONRequestBody defines body for IngestEvents for application/json ContentType.
type IngestEventsJSONRequestBody = IngestRequest

// SaveMoodboardJSONRequestBody defines body for SaveMoodboard for application/json ContentType.
type SaveMoodboardJSONRequestBody = SaveMoodboardRequest

// SubmitOutfitFeedbackJSONRequestBody defines body for SubmitOutfitFeedback for application/json ContentType.
type SubmitOutfitFeedbackJSONRequestBody = FeedbackSubmitRequest

// UpdateProfileJSONRequestBody defines body for UpdateProfile for application/json ContentType.
type UpdateProfileJSONRequestBody = UpdateProfileRequest

// DetectFromPhotoMultipartRequestBody defines body for DetectFromPhoto for multipart/form-data ContentType.
type DetectFromPhotoMultipartRequestBody DetectFromPhotoMultipartBody

// SubmitDetectJobMultipartRequestBody defines body for SubmitDetectJob for multipart/form-data ContentType.
type SubmitDetectJobMultipartRequestBody SubmitDetectJobMultipartBody

// CreateWardrobeItemJSONRequestBody defines body for CreateWardrobeItem for application/json ContentType.
type CreateWardrobeItemJSONRequestBody = DetectedItem

// UpdateWardrobeItemJSONRequestBody defines body for UpdateWardrobeItem for application/json ContentType.
type UpdateWardrobeItemJSONRequestBody = UpdateWardrobeItemRequest

// SearchSimilarProductsJSONRequestBody defines body for SearchSimilarProducts for application/json ContentType.
type SearchSimilarProductsJSONRequestBody = SearchRequest
