/**
 * A persisted clothing item in the user's wardrobe.
 * Returned by GET /v1/wardrobe/items.
 */
export interface WardrobeItem {
  id: string;
  userId: string;
  category: string;
  label: string;
  /** "male" | "female" | "unisex" — defaults to the owner's profile gender at detection time. */
  gender?: 'male' | 'female' | 'unisex';
  /** URL to the flat-lay JPEG image generated by the detection service. */
  imageUrl: string;
  /** URL to the background-removed PNG, stored separately for moodboard compositing. */
  pngImageUrl?: string;
  traits: Record<string, string>;
  createdAt: string;
}
